export default [
  {
    id: "52865",
    name: "Matar Paneer",
    type: "Indian",
    instructions:
      "eat the oil in a frying pan over high heat until it’s shimmering hot. Add the paneer, then turn the heat down a little. Fry until it starts to brown at the edges, then turn it over and brown on each side – the paneer will brown faster than you think, so don’t walk away. Remove the paneer from the pan and drain on kitchen paper.\r\nPut the ginger, cumin, turmeric, ground coriander and chilli in the pan, and fry everything for 1 min. Add the tomatoes, mashing them with the back of a spoon and simmer everything for 5 mins until the sauce smells fragrant. Add a splash of water if it’s too thick. Season well. Add the peas and simmer for a further 2 mins, then stir in the paneer and sprinkle over the garam masala. Divide between two bowls, top with coriander leaves and serve with naan bread, roti or rice.",
    ingredients: [
      "Sunflower Oil",
      "Paneer",
      "Ginger",
      "Cumin",
      "Turmeric",
      "Coriander",
      "Green Chilli",
      "Tomato",
      "Peas",
      "Garam Masala",
      "Coriander",
      "Naan Bread",
    ],
    thumbnail: "https://www.themealdb.com/images/media/meals/xxpqsy1511452222.jpg",
  },

  {
    id: "52777",
    name: "Mediterranean Pasta Salad",
    type: "Seafood",
    instructions:
      "Bring a large saucepan of salted water to the boil\r\nAdd the pasta, stir once and cook for about 10 minutes or as directed on the packet.\r\nMeanwhile, wash the tomatoes and cut into quarters. Slice the olives. Wash the basil.\r\nPut the tomatoes into a salad bowl and tear the basil leaves over them. Add a tablespoon of olive oil and mix.\r\nWhen the pasta is ready, drain into a colander and run cold water over it to cool it quickly.\r\nToss the pasta into the salad bowl with the tomatoes and basil.\r\nAdd the sliced olives, drained mozzarella balls, and chunks of tuna. Mix well and let the salad rest for at least half an hour to allow the flavours to mingle.\r\nSprinkle the pasta with a generous grind of black pepper and drizzle with the remaining olive oil just before serving.",
    ingredients: [
      "mozzarella balls",
      "baby plum tomatoes",
      "fresh basil",
      "farfalle",
      "extra virgin olive oil",
      "Green Olives",
      "tuna",
      "Salt",
      "Pepper",
    ],
    thumbnail: "https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg",
  },
  {
    id: "53014",
    name: "Pizza Express Margherita",
    type: "Italian",
    instructions:
      "1 Preheat the oven to 230°C.\r\n\r\n2 Add the sugar and crumble the fresh yeast into warm water.\r\n\r\n3 Allow the mixture to stand for 10 – 15 minutes in a warm place (we find a windowsill on a sunny day works best) until froth develops on the surface.\r\n\r\n4 Sift the flour and salt into a large mixing bowl, make a well in the middle and pour in the yeast mixture and olive oil.\r\n\r\n5 Lightly flour your hands, and slowly mix the ingredients together until they bind.\r\n\r\n6 Generously dust your surface with flour.\r\n\r\n7 Throw down the dough and begin kneading for 10 minutes until smooth, silky and soft.\r\n\r\n8 Place in a lightly oiled, non-stick baking tray (we use a round one, but any shape will do!)\r\n\r\n9 Spread the passata on top making sure you go to the edge.\r\n\r\n10 Evenly place the mozzarella (or other cheese) on top, season with the oregano and black pepper, then drizzle with a little olive oil.\r\n\r\n11 Cook in the oven for 10 – 12 minutes until the cheese slightly colours.\r\n\r\n12 When ready, place the basil leaf on top and tuck in!",
    ingredients: [
      "Water",
      "Sugar",
      "Yeast",
      "Plain Flour",
      "Salt",
      "Pepper",
      "Olive Oil",
      "Passata",
      "Mozzarella",
      "Oregano",
      "Basil",
      "Black Pepper",
    ],
    thumbnail: "https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg",
  },
  {
    id: "52821",
    name: "Laksa Kind Prawn Noodles",
    type: "Malaysian",
    instructions:
      "Heat the oil in a medium saucepan and add the chilli. Cook for 1 min, then add the curry paste, stir and cook for 1 min more. Dissolve the stock cube in a large jug in 700ml boiling water, then pour into the pan and stir to combine. Tip in the coconut milk and bring to the boil.\r\nAdd the fish sauce and a little seasoning. Toss in the noodles and cook for a further 3-4 mins until softening. Squeeze in the lime juice, add the prawns and cook through until warm, about 2-3 mins. Scatter over some of the coriander.\r\nServe in bowls with the remaining coriander and lime wedges on top for squeezing over.",
    ingredients: [
      "Red chilli",
      "Olive Oil",
      "Thai red curry paste",
      "vegetable stock cube",
      "coconut milk",
      "Fise sauce",
      "Rice noodles",
      "Lime",
      "King prawns",
      "coriander",
    ],
    thumbnail: "https://www.themealdb.com/images/media/meals/rvypwy1503069308.jpg",
  },
];
